### ISSUE TITLE
Search a channel input doesn't work in iPadOS

### ISSUE THREAD

**Issue by adrianengine** [tpkahlon/jackal#2]
Issue: Search channel input not working on iPadOS Safari

Description: On Safari browser running on iPadOS, the `onChange` function of the search input is not being triggered, causing the search feature to not show any results when a search query is entered.

Suggested Solution: Consider using `addEventListener` instead of `onChange` function to fix the issue.

Additional information:

    iPadOS Version: 16.3.1
    Device: iPad Air (5th generation)

**Comment by tpkahlon** [comment]
Hello @adrianengine, Thanks for pointing it out. I am able to reproduce the issue locally and will push a patch to mitigate this.

**Comment by tpkahlon** [comment]
Issue patched in `v3.1.1`.
